on:
  pull_request:
    branches: [ "dev" ]
    types: [opened, synchronize]
  push:
    branches: ["dev"]

jobs:
  prepare:
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Create application.yml in Artifacts
        run: |
          echo "${{ secrets.YML }}" | base64 --decode > application.yml
        shell: bash
      - name: Upload application.yml
        uses: actions/upload-artifact@v4
        with:
          name: application-yml
          path: application.yml

  ci:
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: [prepare]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Download application.yml
        uses: actions/download-artifact@v4
        with:
          name: application-yml
          path: ./src/main/resources
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x gradlew
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle Wrapper
        run: ./gradlew build
      - name: Upload build artifacts  # ✅ 빌드된 JAR 파일 저장
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build/libs/*.jar

  cd:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts  # ✅ 빌드된 JAR 파일 다운로드
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: build/libs
      - name: Docker build & push to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/docker-test .
          docker push ${{ secrets.DOCKER_USERNAME }}/docker-test
          
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/docker-test:latest
            sudo docker stop $(sudo docker ps -q)
            sudo docker run -d --log-driver=syslog -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/docker-test:latest
            sudo docker rm $(sudo docker ps --filter 'status=exited' -q)
            sudo docker image prune -a -f
